version: "3.8"

services:
  api-app:
    platform: linux/amd64
    container_name: api-app
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
#    networks:
#      - web_network
  celery:
    platform: linux/amd64
    build: .
    command: celery -A djangoProject worker --concurrency=1 --loglevel=error --logfile=mediafiles/logs/celery.log
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
#    networks:
#      - web_network
    depends_on:
      - api-app
      - redis
  redis:
    image: redis:7-alpine
#    networks:
#      - web_network

  dashboard:
    platform: linux/amd64
    build: .
    command: celery -A djangoProject --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev
#    networks:
#      - web_network
    depends_on:
      - api-app
      - redis
      - celery
