# Generated by Django 4.1.7 on 2023-05-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BpToYc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operationType', models.CharField(blank=True, max_length=255, null=True)),
                ('idYL', models.CharField(blank=True, max_length=255, null=True)),
                ('idPos', models.CharField(blank=True, max_length=255, null=True)),
                ('FIO', models.CharField(max_length=255)),
                ('posName', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=255, null=True)),
                ('tabNum', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('SNILS', models.CharField(max_length=255)),
                ('dateEmployment', models.CharField(blank=True, max_length=255, null=True)),
                ('dateStartPos', models.CharField(blank=True, max_length=255, null=True)),
                ('edu', models.CharField(blank=True, max_length=255, null=True)),
                ('dateStartEdu', models.CharField(blank=True, max_length=255, null=True)),
                ('dateEndEdu', models.CharField(blank=True, max_length=255, null=True)),
                ('eduInst', models.CharField(blank=True, max_length=255, null=True)),
                ('serialDoc', models.CharField(blank=True, max_length=255, null=True)),
                ('numDoc', models.CharField(blank=True, max_length=255, null=True)),
                ('dateDoc', models.CharField(blank=True, max_length=255, null=True)),
                ('PFM', models.CharField(blank=True, max_length=255, null=True)),
                ('depName', models.CharField(blank=True, max_length=255, null=True)),
                ('timeZone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('learnCode', models.CharField(blank=True, max_length=255, null=True)),
                ('dateStartLearn', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='YcToBp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operationType', models.CharField(max_length=255)),
                ('tabNum', models.CharField(max_length=255)),
                ('FIO', models.CharField(max_length=255, null=True)),
                ('learnCode', models.CharField(max_length=255)),
                ('courseCost', models.CharField(max_length=255)),
                ('eduName', models.CharField(max_length=255)),
                ('eduTime', models.CharField(max_length=255)),
                ('eduUrl', models.CharField(max_length=255)),
                ('eduStatus', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('protocol', models.FileField(blank=True, null=True, upload_to='', verbose_name='Протокол')),
                ('protocolNum', models.CharField(max_length=255)),
                ('protocolDate', models.CharField(max_length=255)),
                ('memberId1', models.CharField(max_length=255)),
                ('memberId2', models.CharField(max_length=255)),
                ('memberId3', models.CharField(max_length=255)),
                ('cert', models.FileField(blank=True, null=True, upload_to='', verbose_name='Удостоверение')),
                ('certDate', models.CharField(max_length=255)),
                ('certNum', models.CharField(max_length=255)),
                ('FGISNum', models.CharField(max_length=255)),
                ('platformStatus', models.CharField(max_length=255)),
                ('bp_to_yc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yc_to_bp', to='restApi.bptoyc')),
            ],
        ),
    ]
