# Generated by Django 4.1.7 on 2023-03-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BC_TO_YC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_proc', models.CharField(max_length=255)),
                ('id_YL', models.CharField(max_length=255)),
                ('id_DOLJNOSTI', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='YC_TO_BC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_proc', models.CharField(max_length=255)),
                ('TAB', models.CharField(max_length=255)),
                ('code_study', models.CharField(max_length=255)),
            ],
        ),
    ]
